on : push 
jobs :
        first-job:
          runs-on : ubuntu-latest
          steps :
                  - run : node --version
                  - run : npm --version
                  - uses : actions/checkout@v4
                  - run : npm ci
                  - run : node index.js